import { Song, Setlist } from "../types";
import { BandMemberOption } from "../utils/repertorioUtils";

// Plantilla de la formación de Bakandeya usada como banda de demostración de la propia
// app: solo debe mostrarse cuando la banda activa es literalmente Bakandeya, nunca como
// fallback para otras bandas.
export const BAKANDEYA_DEMO_MEMBERS: BandMemberOption[] = [
  {
    id: "usr-1",
    name: "Voz / Guitarra",
    instrument: "Voz / Guitarra",
    avatarColor: "var(--acc)",
  },
  {
    id: "usr-2",
    name: "Bajo / Coros",
    instrument: "Bajo / Coros",
    avatarColor: "var(--ok)",
  },
  {
    id: "usr-3",
    name: "Batería / Percusión",
    instrument: "Batería / Percusión",
    avatarColor: "var(--accent-2)",
  },
  {
    id: "usr-4",
    name: "Teclados / Sintes",
    instrument: "Teclados / Sintes",
    avatarColor: "var(--ok)",
  },
  {
    id: "usr-5",
    name: "Vientos / Metales",
    instrument: "Vientos / Metales",
    avatarColor: "var(--acc)",
  },
];

export const SHOW_ITEM_TYPES: Record<
  string,
  { label: string; icon: string; bg: string; text: string }
> = {
  header: {
    label: "Encabezado de Bloque / Sección",
    icon: "⚡",
    bg: "bg-[var(--acc)]/20",
    text: "text-[var(--acc)]",
  },
  presentacion: {
    label: "Presentación Banda / Saludo",
    icon: "🎤",
    bg: "bg-[var(--ok)]/15",
    text: "text-[var(--ok)]",
  },
  intro_tema: {
    label: "Intro / Historia del Tema",
    icon: "🗣️",
    bg: "bg-[var(--acc-soft)]/80",
    text: "text-[var(--acc)]",
  },
  beatbox: {
    label: "Performance Beatbox / Ritmo",
    icon: "🥁",
    bg: "bg-[var(--acc)]/15",
    text: "text-[var(--acc)]",
  },
  solo_performance: {
    label: "Solo de Instrumento / Jam",
    icon: "🎸",
    bg: "bg-[var(--acc-soft)]/60",
    text: "text-[var(--acc)]",
  },
  cambio_instrumento: {
    label: "Cambio Instrumento / Afinación",
    icon: "🔧",
    bg: "bg-[var(--ok)]/15",
    text: "text-[var(--ok)]",
  },
  chapa: {
    label: "Chapa / Discurso con el Público",
    icon: "💬",
    bg: "bg-[var(--acc)]/15",
    text: "text-[var(--acc)]",
  },
  descanso: {
    label: "Pausa / Intermedio / Agua",
    icon: "⏸️",
    bg: "bg-[var(--sunken)]",
    text: "text-[var(--ink-2)]",
  },
  bis: {
    label: "BIS / Parón Pre-Bis",
    icon: "💣",
    bg: "bg-[var(--alert)]/15",
    text: "text-[var(--alert)]",
  },
  otro: {
    label: "Otro Evento del Show",
    icon: "📌",
    bg: "bg-[var(--surface)]/80",
    text: "text-[var(--ink-2)]",
  },
};

// GIF 1x1 transparente para anular la "foto" fantasma que el navegador dibuja por defecto al
// arrastrar con drag-and-drop nativo (HTML5 draggable).
export const TRANSPARENT_DRAG_IMAGE =
  typeof window !== "undefined" ? new window.Image() : null;
if (TRANSPARENT_DRAG_IMAGE) {
  TRANSPARENT_DRAG_IMAGE.src =
    "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBTAA7";
}

export const DEFAULT_SONGS: Song[] = [
  {
    id: "song-cm-1",
    titulo: "Intro (Live Casa México)",
    duracion: "1:30",
    duracionSegundos: 90,
    tonalidad: "Am",
    bpm: 120,
    afinacion: "E Standard",
    albumDisco: "Directo Casa México",
    estadoTema: "listo",
    esVersionCovers: false,
    audioPrincipalUrl: "/audio/samples/sample_01_groove_apertura.mp3",
    audioUrl: "/audio/samples/sample_01_groove_apertura.mp3",
    notasInternas: "Intro del directo en Casa México",
  },
  {
    id: "song-cm-2",
    titulo: "Tema1 (Live Casa México)",
    duracion: "3:45",
    duracionSegundos: 225,
    tonalidad: "Em",
    bpm: 125,
    afinacion: "E Standard",
    albumDisco: "Directo Casa México",
    estadoTema: "listo",
    esVersionCovers: false,
    audioPrincipalUrl: "/audio/samples/sample_03_fuego_asfalto.mp3",
    audioUrl: "/audio/samples/sample_03_fuego_asfalto.mp3",
  },
  {
    id: "song-cm-3",
    titulo: "Reggae Rock Style",
    duracion: "4:10",
    duracionSegundos: 250,
    tonalidad: "Dm",
    bpm: 110,
    afinacion: "E Standard",
    albumDisco: "Directo Casa México",
    estadoTema: "listo",
    esVersionCovers: false,
    audioPrincipalUrl: "/audio/samples/sample_04_brisa_mediterranea.mp3",
    audioUrl: "/audio/samples/sample_04_brisa_mediterranea.mp3",
  },
  {
    id: "song-cm-4",
    titulo: "Ska",
    duracion: "3:20",
    duracionSegundos: 200,
    tonalidad: "Am",
    bpm: 145,
    afinacion: "E Standard",
    albumDisco: "Directo Casa México",
    estadoTema: "listo",
    esVersionCovers: false,
    audioPrincipalUrl: "/audio/samples/sample_05_cierre_triunfal.mp3",
    audioUrl: "/audio/samples/sample_05_cierre_triunfal.mp3",
  },
  {
    id: "song-cm-5",
    titulo: "Llorona",
    duracion: "4:30",
    duracionSegundos: 270,
    tonalidad: "Am",
    bpm: 100,
    afinacion: "E Standard",
    albumDisco: "Directo Casa México",
    estadoTema: "listo",
    esVersionCovers: false,
    audioPrincipalUrl: "/audio/samples/sample_02_balada_medianoche.mp3",
    audioUrl: "/audio/samples/sample_02_balada_medianoche.mp3",
  },
  {
    id: "song-1",
    titulo: "Brisa y Cacharros",
    duracion: "3:30",
    duracionSegundos: 210,
    tonalidad: "Am",
    bpm: 124,
    afinacion: "E Standard",
    albumDisco: "Álbum Debut (2025)",
    estadoTema: "listo",
    esVersionCovers: false,
    enlaceAcordes: "https://drive.google.com",
    notasInternas:
      "Intro con sección de vientos y solo de trompeta. Gran fuerza en estribillos.",
  },
  {
    id: "song-2",
    titulo: "Fuego en la Sala",
    duracion: "4:12",
    duracionSegundos: 252,
    tonalidad: "Em",
    bpm: 138,
    afinacion: "E Standard",
    albumDisco: "Álbum Debut (2025)",
    estadoTema: "listo",
    esVersionCovers: false,
    notasInternas:
      "Subida progresiva al final. Tema estelar de cierre en festival.",
  },
  {
    id: "song-3",
    titulo: "Noches de Garaje",
    duracion: "3:45",
    duracionSegundos: 225,
    tonalidad: "Dm",
    bpm: 115,
    afinacion: "Drop D",
    albumDisco: "EP Cacharros & Ritmo",
    estadoTema: "listo",
    esVersionCovers: false,
    notasInternas: "Afinación especial en guitarra antes de empezar.",
  },
  {
    id: "song-4",
    titulo: "Ska del Norte",
    duracion: "3:15",
    duracionSegundos: 195,
    tonalidad: "A Major",
    bpm: 152,
    afinacion: "E Standard",
    albumDisco: "Single 2026",
    estadoTema: "listo",
    esVersionCovers: false,
    notasInternas:
      "Ritmo acelerado ska. Ideal para subir la energía a mitad del concierto.",
  },
  {
    id: "song-5",
    titulo: "Canto a la Sombra",
    duracion: "5:10",
    duracionSegundos: 310,
    tonalidad: "Bm",
    bpm: 96,
    afinacion: "E Standard",
    albumDisco: "Álbum Debut (2025)",
    estadoTema: "listo",
    esVersionCovers: false,
    notasInternas:
      "Balada rock progresiva con solo de violín de Raúl en la sección central.",
  },
  {
    id: "song-6",
    titulo: "Gira Sin Fin",
    duracion: "4:05",
    duracionSegundos: 245,
    tonalidad: "G Major",
    bpm: 128,
    afinacion: "E Standard",
    albumDisco: "Álbum Debut (2025)",
    estadoTema: "listo",
    esVersionCovers: false,
  },
  {
    id: "song-7",
    titulo: "Mánager Fantasma",
    duracion: "3:50",
    duracionSegundos: 230,
    tonalidad: "Cm",
    bpm: 120,
    afinacion: "E Standard",
    albumDisco: "Inéditas / En Proceso",
    estadoTema: "ensayando",
    esVersionCovers: false,
    notasInternas:
      "Sátira sobre los bots y mánagers virtuales. Ensayando para el próximo EP.",
  },
  {
    id: "song-8",
    titulo: "Maldita Dulzura (Cover)",
    duracion: "3:40",
    duracionSegundos: 220,
    tonalidad: "C Major",
    bpm: 110,
    afinacion: "E Standard",
    albumDisco: "Covers & Versiones",
    estadoTema: "listo",
    esVersionCovers: true,
    notasInternas: "Versión acelerada adaptada a vientos y ritmo ska-rock.",
  },
];

export const DEFAULT_SETLISTS: Setlist[] = [
  {
    id: "setlist-1",
    nombre: "Festival Directo Caña 45 min",
    descripcion:
      "Estructura ágil en 3 bloques (Calentamiento, Nudo y Desenlace) con beatbox y presentación",
    tipoFormato: "festival",
    duracionTotalEstimadaMinutos: 45,
    fechaCreacion: "2026-03-01",
    fechaUltimaEdicion: "2026-08-01",
    items: [
      {
        id: "i-b1",
        tipoItem: "bloque",
        bloqueSubtipo: "header",
        tituloCustom: "Bloque 1: Calentamiento & Arranque",
      },
      {
        id: "i-1",
        songId: "song-1",
        tipoItem: "cancion",
        notaTema: "Arrancar directo sin intro",
      },
      {
        id: "i-2",
        songId: "song-2",
        tipoItem: "cancion",
        notaTema: "Empalmar batería con final de Brisa",
      },
      {
        id: "i-bbx",
        tipoItem: "bloque",
        bloqueSubtipo: "beatbox",
        tituloCustom: "Solo de Percusión / Intro Vocal",
        duracionEstimadaMinutos: 2,
        duracionEstimadaSegundos: 120,
        notaTema:
          "Luz cenital sobre el solista. La base rítmica marca el pulso.",
      },
      {
        id: "i-b2",
        tipoItem: "bloque",
        bloqueSubtipo: "header",
        tituloCustom: "Bloque 2: Nudo & Clímax",
      },
      {
        id: "i-3",
        songId: "song-4",
        tipoItem: "cancion",
        notaTema: "Subidón ska",
      },
      {
        id: "i-4",
        tipoItem: "bloque",
        bloqueSubtipo: "presentacion",
        tituloCustom: "Presentación Banda & Agradecimientos",
        duracionEstimadaMinutos: 2,
        duracionEstimadaSegundos: 120,
        notaTema: "El vocalista habla al público y presenta a los músicos",
      },
      {
        id: "i-5",
        songId: "song-3",
        tipoItem: "cancion",
        notaTema: "Cambio de guitarra a Drop D",
      },
      {
        id: "i-b3",
        tipoItem: "bloque",
        bloqueSubtipo: "header",
        tituloCustom: "Bloque 3: Desenlace & BIS Final",
      },
      {
        id: "i-6",
        songId: "song-6",
        tipoItem: "cancion",
        notaTema: "Estribillo con coros del público",
      },
      {
        id: "i-7",
        tipoItem: "bloque",
        bloqueSubtipo: "bis",
        tituloCustom: "BIS / Cierre de Festival",
        duracionEstimadaMinutos: 1,
        duracionEstimadaSegundos: 60,
        notaTema: "Salida rápida de escenario y vuelta para bis",
      },
      {
        id: "i-8",
        songId: "song-5",
        tipoItem: "cancion",
        notaTema: "Solo final de violín extendido",
      },
    ],
  },
  {
    id: "setlist-2",
    nombre: "Concierto Sala Larga 75 min",
    descripcion:
      "Setlist completo con bloque acústico, solos e intros explicativas",
    tipoFormato: "sala_larga",
    duracionTotalEstimadaMinutos: 75,
    fechaCreacion: "2026-04-10",
    fechaUltimaEdicion: "2026-07-20",
    items: [
      {
        id: "i-20",
        tipoItem: "bloque",
        bloqueSubtipo: "header",
        tituloCustom: "Bloque 1: Bienvenida & Potencia",
      },
      { id: "i-21", songId: "song-1", tipoItem: "cancion" },
      { id: "i-22", songId: "song-6", tipoItem: "cancion" },
      {
        id: "i-intro",
        tipoItem: "bloque",
        bloqueSubtipo: "intro_tema",
        tituloCustom: "Historia / Intro a Noches de Garaje",
        duracionEstimadaMinutos: 1,
        duracionEstimadaSegundos: 60,
        notaTema: "Explicación del origen de la canción",
      },
      { id: "i-23", songId: "song-3", tipoItem: "cancion" },
      {
        id: "i-23b",
        tipoItem: "bloque",
        bloqueSubtipo: "header",
        tituloCustom: "Bloque 2: Acústico & Covers",
      },
      {
        id: "i-24",
        songId: "song-8",
        tipoItem: "cancion",
        notaTema: "Cover festivo",
      },
      {
        id: "i-25",
        tipoItem: "bloque",
        bloqueSubtipo: "chapa",
        tituloCustom: "Chapa Merch & Agradecimientos a la Sala",
        duracionEstimadaMinutos: 3,
        duracionEstimadaSegundos: 180,
      },
      {
        id: "i-26",
        songId: "song-7",
        tipoItem: "cancion",
        notaTema: "Tema nuevo en prueba",
      },
      {
        id: "i-26b",
        tipoItem: "bloque",
        bloqueSubtipo: "header",
        tituloCustom: "Bloque 3: Desenlace & Traca",
      },
      { id: "i-27", songId: "song-5", tipoItem: "cancion" },
      { id: "i-28", songId: "song-4", tipoItem: "cancion" },
      { id: "i-29", songId: "song-2", tipoItem: "cancion" },
    ],
  },
];
