import { EPKConfig, Lead } from '../types';
import { EpkLanguage, DEFAULT_EPK_LANGUAGE, idiomaEpkParaLead } from '../i18n/epkTranslations';

export interface EmailAttachment {
  filename: string;
  contentType: string;
  dataBase64: string;
}

export interface FormattedEmailResult {
  html: string;
  text: string;
  attachments: EmailAttachment[];
}

/**
 * Builds a valid binary PDF 1.4 base64 encoded document for Bakandeya's Dossier & EPK
 */
export function buildBakandeyaDossierPdfBase64(params?: {
  bandName?: string;
  contactEmail?: string;
  phone?: string;
  bandId?: string;
  lang?: EpkLanguage;
}): string {
  const band = params?.bandName || 'Tu Banda';
  const email = params?.contactEmail || '';
  const phone = params?.phone || '';
  // Mismo criterio que en la firma del email: el enlace al EPK siempre lleva su band_id. Antes,
  // sin bandId explícito, caía en 'band-bakandeya': el dossier PDF adjunto en el email de
  // CUALQUIER banda enlazaba al EPK público real de Bakandeya en vez del propio.
  const bandIdPdf = params?.bandId || '';
  // El idioma viaja con el enlace: el EPK abre directamente en la versión que le toca al
  // destinatario en vez de obligarle a buscar el selector.
  const langPdf = params?.lang || DEFAULT_EPK_LANGUAGE;
  const epkUrlPdf = `https://bands-manager.up.railway.app/epk?band=${encodeURIComponent(bandIdPdf)}&lang=${langPdf}`;

  const header = '%PDF-1.4\n';
  const obj1 = '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n';
  const obj2 = '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n';
  const obj3 =
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n';

  const streamLines = [
    'BT',
    '/F1 16 Tf',
    '50 730 Td',
    `(${band.toUpperCase()} - DOSSIER OFICIAL & KIT DE PRENSA) Tj`,
    '/F1 11 Tf',
    '0 -28 Td',
    '(Proyecto de Electronica-Fusion, Electro-Basureo & Directo de Escenario) Tj',
    '0 -20 Td',
    `(Contacto Directo Booking: ${email} | Tel: ${phone}) Tj`,
    '0 -30 Td',
    '------------------------------------------------------------------------- Tj',
    '0 -25 Td',
    '(RESUMEN DEL DOSSIER & FICHA TECNICA 2025) Tj',
    '0 -22 Td',
    '(- Musicos de trayectoria internacional: ex-Cirque du Soleil, STOMP, Toompak) Tj',
    '0 -18 Td',
    '(- Estilo: Percusion reciclada, Balkan, Reggae, Klezmer y DJ Live) Tj',
    '0 -18 Td',
    '(- Directo energico, festivo y muy participativo para todo tipo de publicos) Tj',
    '0 -18 Td',
    '(- Formato versatil: Escenario Principal / Formato Sala / Formato Acustico) Tj',
    '0 -30 Td',
    '(MATERIALES COMPLEMENTARIOS Y ENLACES OFICIALES:) Tj',
    '0 -18 Td',
    '(- Rider Tecnico Completo y Stage Plan) Tj',
    '0 -18 Td',
    '(- Repertorio, audios de estudio y videos de directo en alta calidad) Tj',
    '0 -30 Td',
    `(Kit de Prensa Completo (EPK): ${epkUrlPdf}) Tj`,
    'ET',
  ];

  const streamContent = streamLines.join('\n');
  const streamLength = new TextEncoder().encode(streamContent).length;
  const obj4 = `4 0 obj\n<< /Length ${streamLength} >>\nstream\n${streamContent}\nendstream\nendobj\n`;
  const obj5 = '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n';

  const pos1 = header.length;
  const pos2 = pos1 + obj1.length;
  const pos3 = pos2 + obj2.length;
  const pos4 = pos3 + obj3.length;
  const pos5 = pos4 + obj4.length;
  const startxref = pos5 + obj5.length;

  const xref = `xref
0 6
0000000000 65535 f 
${String(pos1).padStart(10, '0')} 00000 n 
${String(pos2).padStart(10, '0')} 00000 n 
${String(pos3).padStart(10, '0')} 00000 n 
${String(pos4).padStart(10, '0')} 00000 n 
${String(pos5).padStart(10, '0')} 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
${startxref}
%%EOF`;

  const fullPdf = header + obj1 + obj2 + obj3 + obj4 + obj5 + xref;
  const bytes = new TextEncoder().encode(fullPdf);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

/**
 * Cleans any trailing duplicate signatures, contact data, or redundant sign-offs
 * generated by LLMs or previous templates so only the clean message body remains.
 */
export function cleanTrailingPitchSignature(text: string): string {
  if (!text) return '';
  let cleaned = text.trim();

  // Strip markdown trailing hr separators (e.g. ---, ___, ===)
  cleaned = cleaned.replace(/\n\s*[-—_=]{3,}\s*$/g, '').trim();

  // Strip redundant trailing signature blocks with contact details (names, roles, phones, emails)
  const signOffPatterns = [
    /\n+(?:(?:¡?Un saludo(?: cordial)?!?|Atentamente,?|Cordialmente,?|¡?Un (?:fuerte )?abrazo!?|Saludos cordiales,?|Quedamos a vuestra (?:entera )?disposici[oó]n\.?))\s*\n+([\s\S]*)$/i,
    /\n+(?:(?:Booking\s*&\s*Management|Management|Equipo de Booking|Booking Team)[\s\S]*)$/i,
    /\n+(?:(?:📞|📱|✉️|Email:|Tel:|\+34|\b[\w.-]+@[\w.-]+\.\w+\b)[\s\S]*)$/i
  ];

  for (const pat of signOffPatterns) {
    const match = cleaned.match(pat);
    if (match) {
      const idx = cleaned.lastIndexOf(match[0]);
      const signOffWord = match[0].split('\n').map(s => s.trim()).filter(Boolean)[0];
      const isPureSignOff = /^(¡?Un saludo|Atentamente|Cordialmente|¡?Un fuerte abrazo|Saludos)/i.test(signOffWord || '');
      cleaned = cleaned.substring(0, idx).trim() + (isPureSignOff ? `\n\n${signOffWord}` : '');
    }
  }

  return cleaned.trim();
}

export function formatEmailWithSignatureAndDossier(params: {
  pitchText?: string;
  lead?: Partial<Lead> | null;
  epkConfig?: Partial<EPKConfig> | null;
  senderName?: string;
  bandName?: string;
  bandId?: string;
}): FormattedEmailResult {
  const { pitchText, lead, epkConfig, senderName, bandName, bandId } = params;

  // Sin bandName ni contactoBooking.nombre, esto firmaba el email como Bakandeya y usaba su
  // email/teléfono reales (ver isBakandeya/defaultEmail/defaultPhone más abajo) para CUALQUIER
  // banda. Los llamantes actuales ya evitan pasar undefined (ver bandDisplayName en
  // Chatbot.tsx), pero la función no debe depender de eso para no filtrar datos reales.
  const resolvedBandName = bandName || epkConfig?.contactoBooking?.nombre || 'la banda';
  const isBakandeya = resolvedBandName.toLowerCase().includes('bakandeya');
  const defaultEmail = isBakandeya ? 'bakandeya@gmail.com' : `${resolvedBandName.toLowerCase().replace(/[^a-z0-9]/g, '')}@booking.com`;
  const defaultPhone = isBakandeya ? '+34 652 938 521' : '+34 600 000 000';
  const salaName = lead?.nombre_sala || 'vuestra sala';
  const salaCiudad = lead?.ciudad ? ` (${lead.ciudad})` : '';

  // 1. Fallback pitch text if empty
  let rawBody = pitchText?.trim();
  if (!rawBody) {
    rawBody = `Hola equipo de ${salaName},\n\nOs escribimos de parte de ${resolvedBandName}, proyecto de música en directo.\n\nNos encantaría presentar nuestro directo en ${salaName}${salaCiudad} durante nuestra próxima gira.\n\nAdjuntamos a este correo nuestro Dossier Oficial en PDF con rider técnico, trayectoria y propuesta artística para que podáis consultarlo directamente.\n\nQuedamos a vuestra entera disposición para concretar fechas y condiciones.\n\n¡Un saludo!`;
  }

  // Clean trailing duplicate signature if present in text
  const bodyContent = cleanTrailingPitchSignature(rawBody);

  // Check if bodyContent already has HTML
  const isAlreadyHtml = bodyContent.startsWith('<') || bodyContent.startsWith('<!DOCTYPE');
  
  // Format body text paragraphs cleanly.
  const htmlBodyParagraphs = isAlreadyHtml
    ? bodyContent
    : bodyContent
        .split('\n\n')
        .map((paragraph) => {
          const escaped = paragraph
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');
          return `<p style="margin: 0 0 14px 0; line-height: 1.6; color: #1e293b; font-size: 15px;">${escaped.replace(/\n/g, '<br>')}</p>`;
        })
        .join('');

  // 2. Extract Signature details from epkConfig or defaults
  const firma = epkConfig?.firmaEmail;
  const booking = epkConfig?.contactoBooking;

  const remitenteNombre =
    (senderName && senderName.toLowerCase() !== 'equipo' ? senderName : null) ||
    firma?.nombreRemitente ||
    booking?.nombre ||
    (isBakandeya ? 'Bakandeya Management' : 'Equipo de Booking');
  
  const cargo = firma?.cargo || `Booking & Management | ${resolvedBandName}`;
  const textoPie = firma?.textoPie || (isBakandeya ? 'Electrobasureo: ska-balkan y mestizaje sobre percusión reciclada y electrónica' : '');
  const telefono = firma?.telefono || booking?.telefono || defaultPhone;
  const email = firma?.email || booking?.email || defaultEmail;

  const dossierPdfUrl = epkConfig?.dossierPdfUrl || epkConfig?.dossierDocumentUrl || '';
  const dossierPdfName = epkConfig?.dossierPdfName || 'Dossier Bakandeya.pdf';

  const enlaces = epkConfig?.enlacesRedes || {};
  const logoUrl = epkConfig?.logoUrl || (isBakandeya ? 'https://bands-manager.up.railway.app/logo_bakandeya_bueno_sin_fondo.png' : '');

  const resolvedBandId = epkConfig?.bandId || (resolvedBandName.toLowerCase().includes('bakandeya') ? 'band-bakandeya' : resolvedBandName.toLowerCase().replace(/\s+/g, '-'));
  const cleanBandId = resolvedBandId.replace(/^(band|reg)-/, '').toLowerCase();
  
  const bandParam = `?band=${encodeURIComponent(resolvedBandId.startsWith('band-') ? resolvedBandId : `band-${cleanBandId}`)}`;
  const epkLang = idiomaEpkParaLead(lead);
  const webEpkUrl = `https://bands-manager.up.railway.app/epk${bandParam}&lang=${epkLang}`;
  const effectiveEpkLink = webEpkUrl;

  // Build clean, elegant social media links with official badges/logos
  const socialIconsMap: Record<string, { badgeUrl: string; label: string }> = {
    instagram: {
      badgeUrl: 'https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white',
      label: 'Instagram'
    },
    facebook: {
      badgeUrl: 'https://img.shields.io/badge/Facebook-1877F2?style=for-the-badge&logo=facebook&logoColor=white',
      label: 'Facebook'
    },
    tiktok: {
      badgeUrl: 'https://img.shields.io/badge/TikTok-000000?style=for-the-badge&logo=tiktok&logoColor=white',
      label: 'TikTok'
    },
    spotify: {
      badgeUrl: 'https://img.shields.io/badge/Spotify-1DB954?style=for-the-badge&logo=spotify&logoColor=white',
      label: 'Spotify'
    },
    youtube: {
      badgeUrl: 'https://img.shields.io/badge/YouTube-FF0000?style=for-the-badge&logo=youtube&logoColor=white',
      label: 'YouTube'
    },
    appleMusic: {
      badgeUrl: 'https://img.shields.io/badge/Apple_Music-FA243C?style=for-the-badge&logo=apple-music&logoColor=white',
      label: 'Apple Music'
    },
    bandcamp: {
      badgeUrl: 'https://img.shields.io/badge/Bandcamp-629AA9?style=for-the-badge&logo=bandcamp&logoColor=white',
      label: 'Bandcamp'
    },
    website: {
      badgeUrl: 'https://img.shields.io/badge/Web-475569?style=for-the-badge&logo=google-chrome&logoColor=white',
      label: 'Web Oficial'
    },
    whatsapp: {
      badgeUrl: 'https://img.shields.io/badge/WhatsApp-25D366?style=for-the-badge&logo=whatsapp&logoColor=white',
      label: 'WhatsApp'
    }
  };

  // Solo incluir links de redes sociales que están efectivamente configurados (no vacíos/whitespace)
  // No usar defaults: solo mostrar lo que está explícitamente en enlaces
  const buildSocialLink = (platform: string, configUrl?: string): { net: string; label: string; url: string; badgeUrl: string } | null => {
    const url = configUrl && String(configUrl).trim() ? String(configUrl).trim() : '';
    if (!url) return null;

    const map = socialIconsMap[platform as keyof typeof socialIconsMap];
    return {
      net: platform,
      label: map?.label || platform,
      url,
      badgeUrl: map?.badgeUrl || ''
    };
  };

  const socialLinksList: Array<{ net: string; label: string; url: string; badgeUrl: string }> = [
    buildSocialLink('instagram', enlaces.instagram),
    buildSocialLink('facebook', enlaces.facebook),
    buildSocialLink('tiktok', enlaces.tiktok),
    buildSocialLink('spotify', enlaces.spotify),
    buildSocialLink('youtube', enlaces.youtube),
    buildSocialLink('appleMusic', enlaces.appleMusic),
    buildSocialLink('bandcamp', enlaces.bandcamp),
    buildSocialLink('website', enlaces.website),
    (enlaces as any).whatsapp ? {
      net: 'whatsapp',
      label: 'WhatsApp',
      url: `https://wa.me/${String((enlaces as any).whatsapp).replace(/[^0-9]/g, '')}`,
      badgeUrl: socialIconsMap.whatsapp.badgeUrl
    } : null
  ].filter((item): item is { net: string; label: string; url: string; badgeUrl: string } => !!item && !!item.url);

  const activeSocialLinksHtml = ((firma?.incluirIconosRedes ?? true) && socialLinksList.length > 0)
    ? `
      <div style="margin-top: 10px; display: flex; align-items: center; gap: 6px; flex-wrap: wrap;">
        ${socialLinksList.map(b => {
          const raw = String(b.url).trim();
          const href = raw.startsWith('http') ? raw : `https://${raw}`;
          return `<a href="${href}" target="_blank" rel="noopener noreferrer" style="display: inline-block; text-decoration: none; margin-right: 6px; margin-bottom: 4px;">
            <img src="${b.badgeUrl}" alt="${b.label}" height="20" style="height: 20px; border-radius: 4px; display: inline-block; vertical-align: middle;" />
          </a>`;
        }).join('')}
      </div>
    `
    : '';

  const adjuntarDossier = (firma?.adjuntarDossierPorDefecto ?? true);
  const dossierLabel = dossierPdfName ? `Dossier Oficial & Rider (${dossierPdfName})` : 'Dossier Oficial & Kit de Prensa';

  // 3. Construct natural, organically integrated HTML email
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; font-size: 15px; color: #1e293b; line-height: 1.6; background-color: #ffffff; margin: 0; padding: 12px;">
  <div style="max-width: 620px; margin: 0 auto; background: #ffffff;">
    
    <!-- PITCH TEXT -->
    <div style="font-size: 15px; color: #1e293b; line-height: 1.6;">
      ${htmlBodyParagraphs}
    </div>

    <!-- NATURAL ORGANIC SIGNATURE -->
    <div style="margin-top: 20px; padding-top: 14px; border-top: 1px solid #e2e8f0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
      <table cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse;">
        <tr>
          ${logoUrl ? `
          <td valign="top" style="padding-right: 12px; width: 48px;">
            <img src="${logoUrl}" alt="${resolvedBandName}" width="44" height="44" style="width: 44px; height: 44px; border-radius: 8px; object-fit: contain; display: block;" />
          </td>
          ` : ''}
          <td valign="top">
            <div style="font-weight: 700; font-size: 14px; color: #0f172a; line-height: 1.3;">
              ${remitenteNombre}
            </div>
            <div style="color: #475569; font-size: 12px; font-weight: 500; margin-top: 2px;">
              ${cargo}
            </div>
            ${textoPie ? `
            <div style="color: #64748b; font-size: 11px; margin-top: 3px; font-style: italic;">
              ${textoPie}
            </div>
            ` : ''}
            <div style="font-size: 12px; color: #64748b; margin-top: 6px;">
              ${telefono ? `<span><a href="tel:${telefono.replace(/\s+/g, '')}" style="color: #475569; text-decoration: none;">${telefono}</a></span>` : ''}
              ${telefono && email ? ` &nbsp;•&nbsp; ` : ''}
              ${email ? `<span><a href="mailto:${email}" style="color: #0284c7; text-decoration: none;">${email}</a></span>` : ''}
            </div>
          </td>
        </tr>
      </table>

      ${adjuntarDossier ? `
      <div style="margin-top: 10px; font-size: 12px;">
        📁 <a href="${effectiveEpkLink}" target="_blank" rel="noopener noreferrer" style="color: #0284c7; text-decoration: underline; font-weight: 600;">${dossierLabel}</a>
      </div>
      ` : ''}

      ${activeSocialLinksHtml ? `
      <div style="margin-top: 8px; padding-top: 8px; border-top: 1px dotted #e2e8f0; font-size: 12px; color: #64748b;">
        ${activeSocialLinksHtml}
      </div>
      ` : ''}
    </div>

  </div>
</body>
</html>`.trim();

  // 4. Plain text version
  const linksTextArray = [
    dossierPdfUrl ? `EPK / Dossier: ${dossierPdfUrl}` : (adjuntarDossier ? `EPK / Dossier: ${effectiveEpkLink}` : ''),
    enlaces.website ? `Web: ${enlaces.website}` : '',
    enlaces.spotify ? `Spotify: ${enlaces.spotify}` : '',
    enlaces.instagram ? `Instagram: ${enlaces.instagram}` : '',
    enlaces.youtube ? `YouTube: ${enlaces.youtube}` : ''
  ].filter(Boolean);

  const text = `
${bodyContent}

--
${remitenteNombre}
${cargo}
${textoPie ? `${textoPie}\n` : ''}Tel: ${telefono} | Email: ${email}
${linksTextArray.length > 0 ? linksTextArray.join(' | ') : ''}
`.trim();

  // 5. Generate REAL PDF attachment
  const dossierPdfBase64 = buildBakandeyaDossierPdfBase64({
    bandName: resolvedBandName,
    contactEmail: email,
    phone: telefono,
    bandId,
  });

  const attachments: EmailAttachment[] = [
    {
      filename: dossierPdfName.endsWith('.pdf') ? dossierPdfName : `${dossierPdfName}.pdf`,
      contentType: 'application/pdf',
      dataBase64: dossierPdfBase64,
    },
  ];

  return { html, text, attachments };
}

